### ISSUE TITLE
Basic Rendr example

### ISSUE THREAD

**Issue by crwang** [alexindigo/buster-rendr-functional-tests#10]
Hi @alexindigo 

I tried to do a basic rendr example as I want to evaluate using buster for our project but I couldn't seem to get it working easily.

I pushed up an example of what I did here under 07_tests:
https://github.com/crwang/rendr-examples/tree/try-buster-functional

Though the page does display in the the browser, it seems to fail and I'm not able to get further. 

Here's the output on the console:

```
Running 1 tests in 1 runtime ...
Uncaught exception: ./buster/functional_mixin.js:662 Error: The iframe was not loaded correctly, please double check tUncaught exception in [object Object]:

  UncaughtError: ./buster/functional_mixin.js:662 Error: The iframe was not loaded correctly, please double check that the url you requested is available in your test: /index

Timeout: Firefox 38.0, OS X 10.10 | Test Home Page | Click Repos
```

Note: I tried it in our real project and I was able to get past the setup stage, but it didn't seem like the javascript loaded (so I couldn't handle things after doing a `click`).  I'm not sure why I could get past the real set up in our project but couldn't get past it in Rendr's example.

Any help would be appreciated!

Thanks

**Comment by alexindigo** [comment]
Thanks for initiative. I thing the problem that we're using requirejs with our rendr app, and haven't spent enough time making proper examples for requirejs-less buster-functional setup. I started to work on it couple days ago (while I'm on vacation 😅) so it goes slowly. 

Thanks for your example, let me try to play with it, to see if we iron that stuff out.

Thank you.

**Comment by crwang** [comment]
Hi Alex, hope you're able to be resting on your vacation!!

I look forward to seeing what can be done when you have some time.  I can also help out as well.  If we can get our basic tests working, we'll may likely move onto this as it seems to have a lot of advantages and it'd be great to be using other tools that Rendr folks are using.

We do plan on getting into requirejs, especially the bundling that we chatted about months ago, but it hasn't been that high on our priority list yet.

**Comment by alexindigo** [comment]
Btw, how do you run the thing? SO we'd be on the same page here.

Thank you.

**Comment by crwang** [comment]
This is what I did, I'm not sure if it's the standard way, but it's what I could get "working":

1) `cd` into the `07_tests` dir
2) Run the web app: `grunt server`
3) Run buster server: `./node_modules/buster-functional/bin/buster-server`
4) Open browser to localhost:1111 and capture the browser
5) Run the tests: `./node_modules/buster/bin/buster-test`

I had a few different tabs open on my terminal for running different things.

**Comment by alexindigo** [comment]
Can you add `/index` route here and see if it'd work for you?
https://github.com/crwang/rendr-examples/blob/try-buster-functional/07_tests/app/routes.js

Thank you.

**Comment by crwang** [comment]
Hello,

I added added an index in the route, but it didn't give me a different result.  I pushed up the change though into my branch.

**Comment by alexindigo** [comment]
I see you're doing it with karma now,
and I have different vision for this package too,
(making it better with examples is one of the priorities for sure).

I'll close this issue, since it's no longer relevant.
Feel free to ping me if you have more ideas.

Thank you.
