### ISSUE TITLE
request to have a page refresh functionality 

### ISSUE THREAD

**Issue by xtang1234** [alexindigo/buster-rendr-functional-tests#11]
It will be very useful to have page refresh functionality.

Use Case Example:
Go to a SRP page,
Click one photo card to land the PDP page
Refresh the page 
Verify the different behavior

**Comment by alexindigo** [comment]
Have you tried `this.window.location = '/some/url'`?

**Comment by alexindigo** [comment]
Looks like it's no longer an issue. Closing.
Feel free to get back to me if you have any other questions/concerns.
