### ISSUE TITLE
Need more specific details on error reporting

### ISSUE THREAD

**Issue by xtang1234** [alexindigo/buster-rendr-functional-tests#8]
Hello,

This functional test is good thing. However I want to request to have more specific details on error reporting. If I can get the following errors link back to my test case file line number, it will be very useful information for debug.

For example:
Uncaught exception: http://localhost:8080/js/common.js:15410 Uncaught TypeError: Cannot read property 'pageYOffset' of undefined
Uncaught exception: ./buster/bundle-0.7.js:8694 Uncaught AssertionError: [assert.elementExists] Element [object Object] exists on the page

Thank you
Xuemei(Michelle) Tang

**Comment by alexindigo** [comment]
Seems like it's something should be done on buster level. I'm considering a major overhaul for the thing and make it more framework agnostic. So I'll close it for now, since it won't an issue in the next major version.
